### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "firstName": "Anurag",
  "lastName": "Sharma",
  "email": "sharma.user@example.com",
  "password": "User@12345",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "anurag.user@example.com",
  "password": "User@12345"
}

### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "Vikas",
  "lastName": "Author",
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  "profileImageUrl": "https://example.com/avatars/author.png"
}


### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "test3",
  "lastName": "Author",
  "email": "test3.author@example.com",
  "password": "testauthor",
  "profileImageUrl": "https://example.com/avatars/author.png"
}

### Author Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "test3.author@example.com",
  "password": "testauthor"
}



### Create article (AUTHOR)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"698aa613bf75fe800d34be35",
  "title":"test article",
  "category":"programming",
  "content":"content of test2 article"
}



###Read articles of a author
GET http://localhost:4000/author-api/articles/698aa613bf75fe800d34be35



### Update article (AUTHOR)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"698aa613bf75fe800d34be35",
  "articleId":"698aa679bf75fe800d34be39",
  "title":"test2 article updated",
  "category":"programming",
  "content":"content of test1 article updated"
}

### Block User (Admin)
PUT http://localhost:4000/admin-api/block/articles/698acb91554c9b9071f06322

###Unblock User (Admin)
PUT http://localhost:4000/admin-api/un-block/articles/698ab926c3248f40b6b57f0c

### 
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
    "email":"test3.author@example.com",
    "password":"authortest",
    "newPassword":"authortest"
}

### Logout
GET http://localhost:4000/common-api/logout

### Test req
GET http://localhost:4000/test